baseURL = "http://erikmillergalow.com/"
languageCode = "en-us"
title = "Erik Miller-Galow"
theme = "ezhil"

[params]
	# Blog subtitle which appears below blog title. Supports markdown.
	subtitle = "Personal projects and thoughts"
	# Number of posts to show in recent posts list (Optional). Defaults to 10.
	recentPostsCount = 5
	# Content types which are excluded from recent posts and archive page (Optional). Defaults to ["page"]
	excludedTypes = ["page"]
	# Content types which are excludes Disqus comments (Optional). Defaults to ["page"]
	disableDisqusTypes = ["page"]
	# If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
	featherIconsCDN = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 3

[[menu.main]]
name = "Music"
url = "/music"
weight = 4

[[menu.main]]
name = "Links"
url = "/links"
weight = 5

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 6


# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/erikmillergalow"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/erikmillergalow"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/erikmillergalow"

[[params.social]]
name = "Soundcloud"
icon = "headphones"
url = "https://soundcloud.com/erikmillergalow"

# Enable tags.
[taxonomies]
   tag = "tags"
